### ISSUE TITLE
Unexpected response code: 502 for websocket connection

### ISSUE THREAD

**Issue by abovethewater** [vpapakir/uptime-openshift#4]
I get the following error in the console:
WebSocket connection to 'ws://xxx.rhcloud.com/socket.io/1/websocket/IuKwIESH_-nUfYJbr_dA' failed: Error during WebSocket handshake: Unexpected response code: 502

Not sure if this error actually affects anything as it is likely falling back to polling.

Should I be concerned about this error? Can websockets be enabled by using port 8000 / 8443 as per https://www.openshift.com/blogs/paas-websockets

**Comment by qalqi** [comment]
```
socket = io.connect(HOST_REMOTE, {
    transports: ['xhr-polling']
});


```
This issue is resolved by [http://stackoverflow.com/a/11972411/2560946](url)
